'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var types = {
  BEGIN_LOCATION_HOVER: 'BEGIN_LOCATION_HOVER',
  END_LOCATION_HOVER: 'END_LOCATION_HOVER',
  UPDATE_SEARCH_VALUE: 'UPDATE_SEARCH_VALUE',
  UPDATE_SELECTED_LOCATION: 'UPDATE_SELECTED_LOCATION',
  UPDATE_PHONE_INPUT: 'UPDATE_PHONE_INPUT',
  FETCH_LOCATIONS: 'FETCH_LOCATIONS',
  ADD_TEXT_REMINDER: 'ADD_TEXT_REMINDER',
  ADD_EMAIL_REMINDER: 'ADD_EMAIL_REMINDER',
  RESET_REMINDERS: 'RESET_REMINDERS'
};

exports.default = types;