const types = {
  BEGIN_LOCATION_HOVER: 'BEGIN_LOCATION_HOVER',
  END_LOCATION_HOVER: 'END_LOCATION_HOVER',
  UPDATE_SEARCH_VALUE: 'UPDATE_SEARCH_VALUE',
  UPDATE_SELECTED_LOCATION: 'UPDATE_SELECTED_LOCATION',
  UPDATE_PHONE_INPUT: 'UPDATE_PHONE_INPUT',
};

export default types;
